### ISSUE TITLE
ipOverride "" should not go to local host

### ISSUE THREAD

**Issue by afeskoff-godaddy** [afeskoff-godaddy/commerce-common#258]
> [<img alt="bbennett" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.secureserver.net/bbennett) **Authored by [bbennett](https://github.secureserver.net/bbennett)**
_<time datetime="2018-12-01T05:23:21Z" title="Saturday, December 1st 2018, 6:23:21 am +01:00">Dec 1, 2018</time>_
_Closed <time datetime="2019-01-04T19:42:28Z" title="Friday, January 4th 2019, 8:42:28 pm +01:00">Jan 4, 2019</time>_
---

**Comment by vdadeka-godaddy** [comment]
> [<img alt="bbennett" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.secureserver.net/bbennett) **Authored by [bbennett](https://github.secureserver.net/bbennett)**
_<time datetime="2019-01-04T19:42:27Z" title="Friday, January 4th 2019, 8:42:27 pm +01:00">Jan 4, 2019</time>_

---


fixed
