### ISSUE TITLE
getResources should return an empty list not an exception

### ISSUE THREAD

**Issue by afeskoff-godaddy** [afeskoff-godaddy/commerce-common#52]
> [<img alt="gperschbacher" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.secureserver.net/gperschbacher) **Authored by [gperschbacher](https://github.secureserver.net/gperschbacher)**
_<time datetime="2018-01-18T22:54:59Z" title="Thursday, January 18th 2018, 11:54:59 pm +01:00">Jan 18, 2018</time>_
_Closed <time datetime="2018-01-24T16:54:00Z" title="Wednesday, January 24th 2018, 5:54:00 pm +01:00">Jan 24, 2018</time>_
---

getResources should return an empty list not an exception when there are none.  An exception makes sense for getResource but not getResources. It's perfectly valid for an owner to have no resources.

https://github.secureserver.net/commerce/commerce-common/blob/master/store-parent/mysql-store/src/main/java/com/godaddy/commerce/store/mysql/RelationalStore.java#L161

**Comment by vdadeka-godaddy** [comment]
> [<img alt="ghobeika" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.secureserver.net/ghobeika) **Authored by [ghobeika](https://github.secureserver.net/ghobeika)**
_<time datetime="2018-01-18T23:03:14Z" title="Friday, January 19th 2018, 12:03:14 am +01:00">Jan 19, 2018</time>_

---


+1 if you're looking for  all resources, not a specific one it shouldn't be a 404, should just be an {}. 404 should only be returned on bad  lookups for specific items

**Comment by vdadeka-godaddy** [comment]
> [<img alt="ghobeika" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.secureserver.net/ghobeika) **Authored by [ghobeika](https://github.secureserver.net/ghobeika)**
_<time datetime="2018-01-18T23:15:29Z" title="Friday, January 19th 2018, 12:15:29 am +01:00">Jan 19, 2018</time>_

---


Should probably just remove list.empty() from the if statement, and return the list even if it is empty
